version: '3'

services:
  mailer:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "127.0.0.1:8025:8025"  # 健康检查HTTP服务端口
      - "127.0.0.1:25:25"      # SMTP端口（仅本地访问）
    volumes:
      - ./config.json:/app/config.json
      - ./emails:/app/emails
    environment:
      - TZ=Asia/Shanghai
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8025/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
